package claude_test

import (
	"os"
	"strings"
	"testing"

	"github.com/kxn/codex-remote-feishu/internal/adapter/claude"
	"github.com/kxn/codex-remote-feishu/internal/adapter/claude/clauderecord"
	"github.com/kxn/codex-remote-feishu/internal/core/agentproto"
)

// TestTranslatorReplayHelloSimple replays a masked NDJSON fixture through
// the Claude translator and verifies the agentproto event sequence.
// The fixture is generated by the integration test (go test -tags integration).
func TestTranslatorReplayHelloSimple(t *testing.T) {
	fixturePath := "testdata/hello_simple.ndjson"
	if _, err := os.Stat(fixturePath); os.IsNotExist(err) {
		t.Skipf("fixture %s not found; run integration test first: go test -tags integration -run TestClaudeCLIIntegration", fixturePath)
	}

	entries, err := clauderecord.LoadFixture(fixturePath)
	if err != nil {
		t.Fatalf("load fixture: %v", err)
	}

	tr := claude.NewTranslator("replay-test")
	tr.SetDebugLogger(func(format string, args ...any) {
		t.Logf("translator: "+format, args...)
	})

	var allEvents []agentproto.Event
	var allOutbound [][]byte

	for _, entry := range entries {
		switch entry.Direction {
		case clauderecord.DirRecv:
			result, err := tr.ObserveServer(entry.Frame)
			if err != nil {
				t.Logf("observe seq=%d error: %v", entry.Seq, err)
				continue
			}
			allEvents = append(allEvents, result.Events...)
			allOutbound = append(allOutbound, result.OutboundToAgent...)
		case clauderecord.DirSend:
			result, err := tr.ObserveClient(entry.Frame)
			if err != nil {
				continue
			}
			allEvents = append(allEvents, result.Events...)
		}
	}

	t.Logf("replayed %d entries -> %d events, %d outbound frames", len(entries), len(allEvents), len(allOutbound))
	for i, e := range allEvents {
		t.Logf("  event[%d]: kind=%s threadId=%s itemKind=%s delta_len=%d",
			i, e.Kind, e.ThreadID, e.ItemKind, len(e.Delta))
	}

	// Verify expected event kinds appear in order
	assertEventOrder(t, allEvents, []agentproto.EventKind{
		agentproto.EventThreadDiscovered,
		agentproto.EventTurnStarted,
		agentproto.EventItemStarted,
		agentproto.EventItemCompleted,
		agentproto.EventTurnCompleted,
	})

	// Verify turn completed successfully
	turnCompleted := findEventByKind(allEvents, agentproto.EventTurnCompleted)
	if turnCompleted == nil {
		t.Fatal("missing EventTurnCompleted")
	}
	if turnCompleted.Status != "completed" {
		t.Errorf("turn status: got %q, want %q", turnCompleted.Status, "completed")
	}

	// Verify deltas contain text
	var fullText string
	for _, e := range allEvents {
		if e.Kind == agentproto.EventItemDelta && e.ItemKind == "agent_message" {
			fullText += e.Delta
		}
	}
	if !strings.Contains(strings.ToLower(fullText), "hello") {
		t.Errorf("expected delta text to contain 'hello', got %q", fullText)
	}

	// Verify masked CWD propagated correctly
	threadEvent := findEventByKind(allEvents, agentproto.EventThreadDiscovered)
	if threadEvent != nil && threadEvent.CWD != "" {
		if strings.Contains(threadEvent.CWD, "/home/") && !strings.Contains(threadEvent.CWD, "/test/") {
			t.Errorf("CWD appears unmasked: %s", threadEvent.CWD)
		}
	}
}

// TestTranslatorReplayMCPHandshake verifies that MCP control_request messages
// during initialization produce OutboundToAgent frames (the MCP responses).
func TestTranslatorReplayMCPHandshake(t *testing.T) {
	fixturePath := "testdata/hello_simple.ndjson"
	if _, err := os.Stat(fixturePath); os.IsNotExist(err) {
		t.Skipf("fixture %s not found", fixturePath)
	}

	entries, err := clauderecord.LoadFixture(fixturePath)
	if err != nil {
		t.Fatalf("load fixture: %v", err)
	}

	tr := claude.NewTranslator("mcp-test")

	var mcpResponseCount int
	for _, entry := range clauderecord.RecvEntries(entries) {
		result, err := tr.ObserveServer(entry.Frame)
		if err != nil {
			continue
		}
		mcpResponseCount += len(result.OutboundToAgent)
	}

	// We expect at least one outbound frame if there were MCP setup messages.
	// If the recording has no MCP setup (e.g. no MCP servers configured),
	// this is still valid -- just log it.
	t.Logf("MCP handshake produced %d outbound frames", mcpResponseCount)
}

// assertEventOrder checks that the specified event kinds appear in order
// within the event list, allowing other events between them.
func assertEventOrder(t *testing.T, events []agentproto.Event, expected []agentproto.EventKind) {
	t.Helper()
	pos := 0
	for _, e := range events {
		if pos < len(expected) && e.Kind == expected[pos] {
			pos++
		}
	}
	if pos < len(expected) {
		var found []agentproto.EventKind
		for _, e := range events {
			found = append(found, e.Kind)
		}
		t.Errorf("event sequence incomplete: matched %d/%d expected kinds\nexpected: %v\nfound:    %v",
			pos, len(expected), expected, found)
	}
}

func findEventByKind(events []agentproto.Event, kind agentproto.EventKind) *agentproto.Event {
	for i := range events {
		if events[i].Kind == kind {
			return &events[i]
		}
	}
	return nil
}
