// Code generated by scripts/managedshim/prepare-vscode-shim-embed.sh; DO NOT EDIT.

//go:build linux && arm64

package embed

import _ "embed"

//go:embed assets/vscode-shim-linux-arm64.zst
var embeddedManagedShim_linux_arm64 []byte

func init() {
	register(Asset{
		SourceDigest: "80c11579854575504db6da8618c51c88f1ad61de355769476a77ed61730ca0a4",
		SHA256:       "2b88af0b2fc5d956c354bc12caf87989baaeb649257605ab3248521ea45cce9d",
		Zstd:         embeddedManagedShim_linux_arm64,
	})
}
