// Code generated by scripts/managedshim/prepare-vscode-shim-embed.sh; DO NOT EDIT.

//go:build linux && arm64

package embed

import _ "embed"

//go:embed assets/vscode-shim-linux-arm64.zst
var embeddedManagedShim_linux_arm64 []byte

func init() {
	register(Asset{
		SourceDigest: "6fc7261a7896953ffbeb6b9533ca79dbd93a9432c2d5aff9d2127acd497057ba",
		SHA256:       "a20f55c93ae4b6f22b87617cef40a5b302cb15fea998d240cd813e5947915279",
		Zstd:         embeddedManagedShim_linux_arm64,
	})
}
