// Code generated by scripts/managedshim/prepare-vscode-shim-embed.sh; DO NOT EDIT.

//go:build darwin && amd64

package embed

import _ "embed"

//go:embed assets/vscode-shim-darwin-amd64.zst
var embeddedManagedShim_darwin_amd64 []byte

func init() {
	register(Asset{
		SourceDigest: "6fc7261a7896953ffbeb6b9533ca79dbd93a9432c2d5aff9d2127acd497057ba",
		SHA256:       "71c282e634c212cfa1ce9c6c2738b9da709e90e377b93ba1ccd10707b64395a0",
		Zstd:         embeddedManagedShim_darwin_amd64,
	})
}
