// Code generated by scripts/managedshim/prepare-vscode-shim-embed.sh; DO NOT EDIT.

//go:build windows && amd64

package embed

import _ "embed"

//go:embed assets/vscode-shim-windows-amd64.zst
var embeddedManagedShim_windows_amd64 []byte

func init() {
	register(Asset{
		SourceDigest: "80c11579854575504db6da8618c51c88f1ad61de355769476a77ed61730ca0a4",
		SHA256:       "900452fba590754334fee4b23467b32454eff69efa1ddfafc07b66b8840c180e",
		Zstd:         embeddedManagedShim_windows_amd64,
	})
}
