// Code generated by scripts/managedshim/prepare-vscode-shim-embed.sh; DO NOT EDIT.

//go:build windows && amd64

package embed

import _ "embed"

//go:embed assets/vscode-shim-windows-amd64.zst
var embeddedManagedShim_windows_amd64 []byte

func init() {
	register(Asset{
		SourceDigest: "6fc7261a7896953ffbeb6b9533ca79dbd93a9432c2d5aff9d2127acd497057ba",
		SHA256:       "a925ffff7a9e9d5a2fd0fc2e65e66fd320054d6bc94f6c4af92ef01190e86342",
		Zstd:         embeddedManagedShim_windows_amd64,
	})
}
