// Code generated by scripts/managedshim/prepare-vscode-shim-embed.sh; DO NOT EDIT.

//go:build darwin && arm64

package embed

import _ "embed"

//go:embed assets/vscode-shim-darwin-arm64.zst
var embeddedManagedShim_darwin_arm64 []byte

func init() {
	register(Asset{
		SourceDigest: "6fc7261a7896953ffbeb6b9533ca79dbd93a9432c2d5aff9d2127acd497057ba",
		SHA256:       "6a95ce48df04b0f21c26e9c233db7ab6c7153aff0f94e7fff2fcc988d9a8f0f9",
		Zstd:         embeddedManagedShim_darwin_arm64,
	})
}
