// Code generated by scripts/managedshim/prepare-vscode-shim-embed.sh; DO NOT EDIT.

//go:build darwin && arm64

package embed

import _ "embed"

//go:embed assets/vscode-shim-darwin-arm64.zst
var embeddedManagedShim_darwin_arm64 []byte

func init() {
	register(Asset{
		SourceDigest: "80c11579854575504db6da8618c51c88f1ad61de355769476a77ed61730ca0a4",
		SHA256:       "b247e526f1eaa6d61d45716d24e5770f8885ab4f8c4cdeb9d283a64463e5ae40",
		Zstd:         embeddedManagedShim_darwin_arm64,
	})
}
