// Code generated by scripts/managedshim/prepare-vscode-shim-embed.sh; DO NOT EDIT.

//go:build linux && amd64

package embed

import _ "embed"

//go:embed assets/vscode-shim-linux-amd64.zst
var embeddedManagedShim_linux_amd64 []byte

func init() {
	register(Asset{
		SourceDigest: "80c11579854575504db6da8618c51c88f1ad61de355769476a77ed61730ca0a4",
		SHA256:       "0bd23d641b60253475e20ffd19b49711da3a1766242cb0f7008432b5920d6d3e",
		Zstd:         embeddedManagedShim_linux_amd64,
	})
}
