// Code generated by scripts/managedshim/prepare-vscode-shim-embed.sh; DO NOT EDIT.

//go:build darwin && amd64

package embed

import _ "embed"

//go:embed assets/vscode-shim-darwin-amd64.zst
var embeddedManagedShim_darwin_amd64 []byte

func init() {
	register(Asset{
		SourceDigest: "80c11579854575504db6da8618c51c88f1ad61de355769476a77ed61730ca0a4",
		SHA256:       "8bb0de93c694229c1673f1e74f0b34c91f2f0def18572758c01fe21952d07f3c",
		Zstd:         embeddedManagedShim_darwin_amd64,
	})
}
