// Code generated by scripts/managedshim/prepare-vscode-shim-embed.sh; DO NOT EDIT.

//go:build linux && amd64

package embed

import _ "embed"

//go:embed assets/vscode-shim-linux-amd64.zst
var embeddedManagedShim_linux_amd64 []byte

func init() {
	register(Asset{
		SourceDigest: "6fc7261a7896953ffbeb6b9533ca79dbd93a9432c2d5aff9d2127acd497057ba",
		SHA256:       "960137fba488ae6702e363c6b7ec053ddbbcb183dfc3e63582e810f45a1ff0df",
		Zstd:         embeddedManagedShim_linux_amd64,
	})
}
