// Code generated by scripts/upgradeshim/prepare-upgrade-shim-embed.sh; DO NOT EDIT.

//go:build darwin && arm64

package embed

import _ "embed"

//go:embed assets/upgrade-shim-darwin-arm64.zst
var embeddedUpgradeShim_darwin_arm64 []byte

func init() {
	register(Asset{
		SourceDigest: "3674e30e82e0fe10a99926bbd83ca18e4470f3ced105327f2937f3889c382558",
		SHA256:       "e8acc93f8a2d2eebc0f1eb30cc73dc7680cfa0244348281c440e5a8f061bf6f6",
		Zstd:         embeddedUpgradeShim_darwin_arm64,
	})
}
