// Code generated by scripts/upgradeshim/prepare-upgrade-shim-embed.sh; DO NOT EDIT.

//go:build windows && amd64

package embed

import _ "embed"

//go:embed assets/upgrade-shim-windows-amd64.zst
var embeddedUpgradeShim_windows_amd64 []byte

func init() {
	register(Asset{
		SourceDigest: "cf461767b7e97d066a0979dcda4a66391fe7d7610c9aca863e3cec7e968f7a8c",
		SHA256:       "e66d7958d8adc95cc029511159872aa1a6b0b459ed8c0eabb0972b4f585c8941",
		Zstd:         embeddedUpgradeShim_windows_amd64,
	})
}
