// Code generated by scripts/upgradeshim/prepare-upgrade-shim-embed.sh; DO NOT EDIT.

//go:build linux && arm64

package embed

import _ "embed"

//go:embed assets/upgrade-shim-linux-arm64.zst
var embeddedUpgradeShim_linux_arm64 []byte

func init() {
	register(Asset{
		SourceDigest: "cf461767b7e97d066a0979dcda4a66391fe7d7610c9aca863e3cec7e968f7a8c",
		SHA256:       "0f08fd1ccc845342ea452ecfd86a4d03c197c6494bdb80a75ecc4030815e75ea",
		Zstd:         embeddedUpgradeShim_linux_arm64,
	})
}
