// Code generated by scripts/upgradeshim/prepare-upgrade-shim-embed.sh; DO NOT EDIT.

//go:build linux && amd64

package embed

import _ "embed"

//go:embed assets/upgrade-shim-linux-amd64.zst
var embeddedUpgradeShim_linux_amd64 []byte

func init() {
	register(Asset{
		SourceDigest: "cf461767b7e97d066a0979dcda4a66391fe7d7610c9aca863e3cec7e968f7a8c",
		SHA256:       "415f5fb4e5a6088e92a202e1beea20142dd6218e1d873ed291cfd2dd6bdf7cc6",
		Zstd:         embeddedUpgradeShim_linux_amd64,
	})
}
