// Code generated by scripts/upgradeshim/prepare-upgrade-shim-embed.sh; DO NOT EDIT.

//go:build linux && arm64

package embed

import _ "embed"

//go:embed assets/upgrade-shim-linux-arm64.zst
var embeddedUpgradeShim_linux_arm64 []byte

func init() {
	register(Asset{
		SourceDigest: "b0fec7e78c282b3df27f96ebe317768b939ae61965966239f223caee2f32b424",
		SHA256:       "042b194f7be875f8c0c84deb05ce87e2b275b7a8ad50d5e8b343cd0e06bc468e",
		Zstd:         embeddedUpgradeShim_linux_arm64,
	})
}
