// Code generated by scripts/upgradeshim/prepare-upgrade-shim-embed.sh; DO NOT EDIT.

//go:build darwin && amd64

package embed

import _ "embed"

//go:embed assets/upgrade-shim-darwin-amd64.zst
var embeddedUpgradeShim_darwin_amd64 []byte

func init() {
	register(Asset{
		SourceDigest: "b0fec7e78c282b3df27f96ebe317768b939ae61965966239f223caee2f32b424",
		SHA256:       "f376aa7567cb21749da7557f2f6af7eb6b942d4984a954e380f7e0f9ea1aa954",
		Zstd:         embeddedUpgradeShim_darwin_amd64,
	})
}
