// Code generated by scripts/upgradeshim/prepare-upgrade-shim-embed.sh; DO NOT EDIT.

//go:build darwin && amd64

package embed

import _ "embed"

//go:embed assets/upgrade-shim-darwin-amd64.zst
var embeddedUpgradeShim_darwin_amd64 []byte

func init() {
	register(Asset{
		SourceDigest: "cf461767b7e97d066a0979dcda4a66391fe7d7610c9aca863e3cec7e968f7a8c",
		SHA256:       "d67af1ceb53f0c4488426b1ed1127f54c1c6695702f4dc88f3c9f74d5d2e8c06",
		Zstd:         embeddedUpgradeShim_darwin_amd64,
	})
}
