// Code generated by scripts/upgradeshim/prepare-upgrade-shim-embed.sh; DO NOT EDIT.

//go:build darwin && arm64

package embed

import _ "embed"

//go:embed assets/upgrade-shim-darwin-arm64.zst
var embeddedUpgradeShim_darwin_arm64 []byte

func init() {
	register(Asset{
		SourceDigest: "b0fec7e78c282b3df27f96ebe317768b939ae61965966239f223caee2f32b424",
		SHA256:       "d79dfceb369ef2662a2e480d34f53dad3068e96a43c8ad9c02ea8d1f6138af0d",
		Zstd:         embeddedUpgradeShim_darwin_arm64,
	})
}
