// Code generated by scripts/upgradeshim/prepare-upgrade-shim-embed.sh; DO NOT EDIT.

//go:build windows && amd64

package embed

import _ "embed"

//go:embed assets/upgrade-shim-windows-amd64.zst
var embeddedUpgradeShim_windows_amd64 []byte

func init() {
	register(Asset{
		SourceDigest: "b0fec7e78c282b3df27f96ebe317768b939ae61965966239f223caee2f32b424",
		SHA256:       "2b073a120e0b51d271621081a10733f3394f6441d85075c23e64919a04bac40e",
		Zstd:         embeddedUpgradeShim_windows_amd64,
	})
}
