// Code generated by scripts/upgradeshim/prepare-upgrade-shim-embed.sh; DO NOT EDIT.

//go:build linux && amd64

package embed

import _ "embed"

//go:embed assets/upgrade-shim-linux-amd64.zst
var embeddedUpgradeShim_linux_amd64 []byte

func init() {
	register(Asset{
		SourceDigest: "b0fec7e78c282b3df27f96ebe317768b939ae61965966239f223caee2f32b424",
		SHA256:       "c8b74f971b3d7dd8cc354611310cccc0a527a18edff3e8a9070d1aeca93a8f65",
		Zstd:         embeddedUpgradeShim_linux_amd64,
	})
}
