// Code generated by scripts/upgradeshim/prepare-upgrade-shim-embed.sh; DO NOT EDIT.

//go:build darwin && arm64

package embed

import _ "embed"

//go:embed assets/upgrade-shim-darwin-arm64.zst
var embeddedUpgradeShim_darwin_arm64 []byte

func init() {
	register(Asset{
		SourceDigest: "cf461767b7e97d066a0979dcda4a66391fe7d7610c9aca863e3cec7e968f7a8c",
		SHA256:       "1cd1809e3174dede9dfced68bea4467a888ce5890c10415d3afecb1fc821adad",
		Zstd:         embeddedUpgradeShim_darwin_arm64,
	})
}
