#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
PACKAGE_DIR="${ROOT_DIR}/internal/managedshim/embed"
ASSET_DIR="${PACKAGE_DIR}/assets"
GOOS_VALUE="${1:-${GOOS:-$(go env GOOS)}}"
GOARCH_VALUE="${2:-${GOARCH:-$(go env GOARCH)}}"

if ! command -v zstd >/dev/null 2>&1; then
  echo "zstd is required to prepare managed shim assets" >&2
  exit 1
fi

tmp_dir="$(mktemp -d)"
cleanup() {
  rm -rf "${tmp_dir}"
}
trap cleanup EXIT

asset_name="vscode-shim-${GOOS_VALUE}-${GOARCH_VALUE}"
binary_path="${tmp_dir}/${asset_name}"
if [[ "${GOOS_VALUE}" == "windows" ]]; then
  binary_path="${binary_path}.exe"
fi

source_digest="$(
  find "${ROOT_DIR}/cmd/vscode-shim" "${ROOT_DIR}/internal/app/vscodeshim" "${ROOT_DIR}/internal/managedshim" \
    -type f -name '*.go' \
    ! -path "${ROOT_DIR}/internal/managedshim/embed/*" \
    -print0 |
    sort -z |
    xargs -0 sha256sum |
    sha256sum |
    awk '{print $1}'
)"

CGO_ENABLED=0 GOOS="${GOOS_VALUE}" GOARCH="${GOARCH_VALUE}" \
  go build -trimpath -ldflags "-s -w" -o "${binary_path}" ./cmd/vscode-shim

binary_sha256="$(
  sha256sum "${binary_path}" | awk '{print $1}'
)"

mkdir -p "${ASSET_DIR}"
compressed_path="${ASSET_DIR}/${asset_name}.zst"
zstd -19 -q -f -o "${compressed_path}" "${binary_path}"

generated_go="${PACKAGE_DIR}/managed_shim_${GOOS_VALUE}_${GOARCH_VALUE}_embed.go"
cat > "${generated_go}" <<EOF
// Code generated by scripts/managedshim/prepare-vscode-shim-embed.sh; DO NOT EDIT.

//go:build ${GOOS_VALUE} && ${GOARCH_VALUE}

package embed

import _ "embed"

//go:embed assets/$(basename "${compressed_path}")
var embeddedManagedShim_${GOOS_VALUE}_${GOARCH_VALUE} []byte

func init() {
	register(Asset{
		SourceDigest: "${source_digest}",
		SHA256:       "${binary_sha256}",
		Zstd:         embeddedManagedShim_${GOOS_VALUE}_${GOARCH_VALUE},
	})
}
EOF

gofmt -w "${generated_go}"
echo "prepared managed shim asset for ${GOOS_VALUE}/${GOARCH_VALUE}" >&2
