package gateway

import "strings"

const (
	cardActionPayloadKeyKind                  = "kind"
	cardActionPayloadKeyInstanceID            = "instance_id"
	cardActionPayloadKeyWorkspaceKey          = "workspace_key"
	cardActionPayloadKeyThreadID              = "thread_id"
	cardActionPayloadKeyTurnID                = "turn_id"
	cardActionPayloadKeyViewMode              = "view_mode"
	cardActionPayloadKeyPage                  = "page"
	cardActionPayloadKeyReturnPage            = "return_page"
	cardActionPayloadKeyAllowCrossWorkspace   = "allow_cross_workspace"
	cardActionPayloadKeyPromptID              = "prompt_id"
	cardActionPayloadKeyOptionID              = "option_id"
	cardActionPayloadKeyRequestID             = "request_id"
	cardActionPayloadKeyRequestType           = "request_type"
	cardActionPayloadKeyRequestOptionID       = "request_option_id"
	cardActionPayloadKeyRequestAnswers        = "request_answers"
	cardActionPayloadKeyRequestRevision       = "request_revision"
	cardActionPayloadKeyRequestControl        = "request_control"
	cardActionPayloadKeyQuestionID            = "question_id"
	cardActionPayloadKeyCommandID             = "command_id"
	cardActionPayloadKeyActionKind            = "action_kind"
	cardActionPayloadKeyActionArg             = "action_arg"
	cardActionPayloadKeyActionArgPrefix       = "action_arg_prefix"
	cardActionPayloadKeyFieldName             = "field_name"
	cardActionPayloadKeyPickerID              = "picker_id"
	cardActionPayloadKeyEntryName             = "entry_name"
	cardActionPayloadKeyTargetValue           = "target_value"
	cardActionPayloadKeyDaemonLifecycleID     = "daemon_lifecycle_id"
	cardPathPickerDirectorySelectFieldName    = "path_picker_directory"
	cardPathPickerFileSelectFieldName         = "path_picker_file"
	cardTargetPickerModeFieldName             = "target_picker_mode"
	cardTargetPickerWorkspaceFieldName        = "target_picker_workspace"
	cardTargetPickerSessionFieldName          = "target_picker_session"
	cardTargetPickerSourceFieldName           = "target_picker_source"
	cardSelectionThreadFieldName              = "selection_thread"
	cardThreadHistoryTurnFieldName            = "thread_history_turn"
	cardActionPayloadDefaultCommandFieldName  = "command_args"
	cardActionKindAttachInstance              = "attach_instance"
	cardActionKindAttachWorkspace             = "attach_workspace"
	cardActionKindUseThread                   = "use_thread"
	cardActionKindShowScopedThreads           = "show_scoped_threads"
	cardActionKindShowThreads                 = "show_threads"
	cardActionKindShowAllThreads              = "show_all_threads"
	cardActionKindShowAllThreadWorkspaces     = "show_all_thread_workspaces"
	cardActionKindShowRecentThreadWorkspaces  = "show_recent_thread_workspaces"
	cardActionKindShowWorkspaceThreads        = "show_workspace_threads"
	cardActionKindShowAllWorkspaces           = "show_all_workspaces"
	cardActionKindShowRecentWorkspaces        = "show_recent_workspaces"
	cardActionKindKickThreadConfirm           = "kick_thread_confirm"
	cardActionKindKickThreadCancel            = "kick_thread_cancel"
	cardActionKindRequestRespond              = "request_respond"
	cardActionKindRequestControl              = "request_control"
	cardActionKindPageAction                  = "page_action"
	cardActionKindUpgradeOwnerFlow            = "upgrade_owner_flow"
	cardActionKindVSCodeMigrateOwnerFlow      = "vscode_migrate_owner_flow"
	cardActionKindPlanProposal                = "plan_proposal"
	cardActionKindPageSubmit                  = "page_submit"
	cardActionKindSubmitRequestForm           = "submit_request_form"
	cardActionKindPathPickerEnter             = "path_picker_enter"
	cardActionKindPathPickerUp                = "path_picker_up"
	cardActionKindPathPickerSelect            = "path_picker_select"
	cardActionKindPathPickerConfirm           = "path_picker_confirm"
	cardActionKindPathPickerCancel            = "path_picker_cancel"
	cardActionKindTargetPickerSelectMode      = "target_picker_select_mode"
	cardActionKindTargetPickerSelectSource    = "target_picker_select_source"
	cardActionKindTargetPickerSelectWorkspace = "target_picker_select_workspace"
	cardActionKindTargetPickerSelectSession   = "target_picker_select_session"
	cardActionKindTargetPickerOpenPathPicker  = "target_picker_open_path_picker"
	cardActionKindTargetPickerBack            = "target_picker_back"
	cardActionKindTargetPickerCancel          = "target_picker_cancel"
	cardActionKindTargetPickerConfirm         = "target_picker_confirm"
	cardActionKindHistoryPage                 = "history_page"
	cardActionKindHistoryDetail               = "history_detail"
)

func actionPayloadKind(value map[string]any) string {
	return strings.TrimSpace(stringMapValue(value, cardActionPayloadKeyKind))
}
