// Code generated by scripts/shim/prepare-shim-embed.sh; DO NOT EDIT.

//go:build darwin && arm64

package embed

import _ "embed"

//go:embed assets/codex-remote-shim-darwin-arm64.zst
var embeddedShim_darwin_arm64 []byte

func init() {
	register(Asset{
		SourceDigest: "9fa46a54bc08812358213bca0cad61fd71577fe5d3faad8d86060239d57185dc",
		SHA256:       "09bb6c978730a7982f664148f03c1ecba1e3a6ce5a4caf3f0a492a677703502a",
		Zstd:         embeddedShim_darwin_arm64,
	})
}
