// Code generated by scripts/shim/prepare-shim-embed.sh; DO NOT EDIT.

//go:build windows && amd64

package embed

import _ "embed"

//go:embed assets/codex-remote-shim-windows-amd64.zst
var embeddedShim_windows_amd64 []byte

func init() {
	register(Asset{
		SourceDigest: "9fa46a54bc08812358213bca0cad61fd71577fe5d3faad8d86060239d57185dc",
		SHA256:       "0ba2f8b253e09a188267b07f1a2c17714b17a51ea0a0fa740a2d7268361bbdce",
		Zstd:         embeddedShim_windows_amd64,
	})
}
