// Code generated by scripts/shim/prepare-shim-embed.sh; DO NOT EDIT.

//go:build linux && amd64

package embed

import _ "embed"

//go:embed assets/codex-remote-shim-linux-amd64.zst
var embeddedShim_linux_amd64 []byte

func init() {
	register(Asset{
		SourceDigest: "9fa46a54bc08812358213bca0cad61fd71577fe5d3faad8d86060239d57185dc",
		SHA256:       "7dd195fe56db88aff75eb67383611d8ed442e28ea5f873a751bb83382b9f0446",
		Zstd:         embeddedShim_linux_amd64,
	})
}
