// Code generated by scripts/shim/prepare-shim-embed.sh; DO NOT EDIT.

//go:build linux && arm64

package embed

import _ "embed"

//go:embed assets/codex-remote-shim-linux-arm64.zst
var embeddedShim_linux_arm64 []byte

func init() {
	register(Asset{
		SourceDigest: "9fa46a54bc08812358213bca0cad61fd71577fe5d3faad8d86060239d57185dc",
		SHA256:       "2a3664851879dcd8a4828080af9b0b5539418d29d9e3bb164ea27da38d425d0b",
		Zstd:         embeddedShim_linux_arm64,
	})
}
