// Code generated by scripts/shim/prepare-shim-embed.sh; DO NOT EDIT.

//go:build darwin && amd64

package embed

import _ "embed"

//go:embed assets/codex-remote-shim-darwin-amd64.zst
var embeddedShim_darwin_amd64 []byte

func init() {
	register(Asset{
		SourceDigest: "9fa46a54bc08812358213bca0cad61fd71577fe5d3faad8d86060239d57185dc",
		SHA256:       "0b4c476c9e17466d19ce816a340c3b46c280c0078ab88f39120d5f3c23916633",
		Zstd:         embeddedShim_darwin_amd64,
	})
}
